// Raw vocabulary pulled from the four flashcard decks.
// Fields: [dutch, english, dutchSentence, englishSentence, deck]
const RAW_CARDS = [
// --- Mock 1 ---
["rustig","quiet","De buurt is heel rustig.","The neighbourhood is very quiet.",1],
["plek/plaats","place","Is hier nog een plek vrij?","Is there a place free here?",1],
["nadenken","think hard","Ik moet even nadenken.","I have to think for a moment.",1],
["inhoud","contents","De inhoud van het boek is goed.","The contents of the book are good.",1],
["planning","planning","Wat is je planning voor vandaag?","What is your planning for today?",1],
["manier","way","Op deze manier werkt het beter.","This way it works better.",1],
["beginnen","start","De les begint om tien uur.","The class starts at ten o'clock.",1],
["verschillende","various","Er zijn verschillende kleuren.","There are various colors.",1],
["bladzijde/pagina","page","Op welke bladzijde staan we?","What page are we on?",1],
["opnieuw","again and again","Probeer het opnieuw.","Try it again.",1],
["onthouden","remember","Kun je dit onthouden?","Can you remember this?",1],
["uitzoeken","find out","Ik moet dit uitzoeken.","I have to find this out.",1],
["pauze","break","We hebben een korte pauze.","We have a short break.",1],
["omgeving","environment","De omgeving is mooi.","The environment is beautiful.",1],
["uitleggen","explain","Kun je dit uitleggen?","Can you explain this?",1],
["tekst","text","Lees deze tekst.","Read this text.",1],
["belangrijk","important","Dit is heel belangrijk.","This is very important.",1],
["het eerste","first","Dit is het eerste boek.","This is the first book.",1],
["bepalen/besluiten","decide","Je moet zelf besluiten.","You have to decide yourself.",1],
["wanneer","when","Wanneer kom je thuis?","When are you coming home?",1],
["of","or","Wil je thee of koffie?","Do you want tea or coffee?",1],
["een beetje","little bit","Ik spreek een beetje Nederlands.","I speak a little bit of Dutch.",1],
["neem","take","Neem een stoel.","Take a chair.",1],
["dorpsbewoner","village residents","De dorpsbewoners kennen elkaar.","The village residents know each other.",1],
["rondom","around","Rondom het huis staan bomen.","Around the house there are trees.",1],
["oproepen","a call","Hij krijgt een oproep van de dokter.","He gets a call from the doctor.",1],
["jaarlijkse","yearly","Dit is de jaarlijkse vergadering.","This is the yearly meeting.",1],
["weghalen","remove","Kun je dit weghalen?","Can you remove this?",1],
["wegslepen","tow away","Ze willen mijn auto wegslepen.","They want to tow my car away.",1],
["daarom","that's why","Het regent, daarom blijf ik thuis.","It is raining, that's why I stay home.",1],
["verdieping/etage","floor","Ik woon op de derde verdieping.","I live on the third floor.",1],
["gekocht/kopen","(past) bought / buy","Ik heb een nieuw boek gekocht.","I bought a new book.",1],
["betalen","pay","Kan ik met pin betalen?","Can I pay by card?",1],
["bezorging","delivery","De bezorging is gratis.","The delivery is free.",1],
["levertijd","delivery time","Wat is de levertijd?","What is the delivery time?",1],
["klantenservice","customer service","Bel de klantenservice.","Call customer service.",1],
["meenemen","take along","Vergeet je paraplu niet mee te nemen.","Do not forget to take your umbrella along.",1],
["zwemkleding","swimming costume","Vergeet je zwemkleding niet.","Don't forget your swimming costume.",1],
["handdoek","towel","Neem een schone handdoek mee.","Take a clean towel along.",1],
["extra/meer","more","Wil je nog extra koffie?","Do you want extra coffee?",1],
["aanraden/adviseren","advise","Ik kan dit boek aanraden.","I can recommend this book.",1],
["meemogen","may join","Mag ik meegaan met de bus?","May I join on the bus?",1],
["aanmelden","register","Je kunt je online aanmelden.","You can register online.",1],
["vragen","questions","Mag ik je iets vragen?","May I ask you something?",1],
["portier","porter","De portier staat bij de deur.","The porter stands at the door.",1],
["bureau","desk","Mijn bureau is opgeruimd.","My desk is tidy.",1],
["trein","train","De trein vertrekt om acht uur.","The train leaves at eight.",1],
["vergeten","forget","Ik ben mijn sleutels vergeten.","I forgot my keys.",1],
["merken","notice","Ik merk dat je moe bent.","I notice that you are tired.",1],
["ophalen","pick up","Ik kom je om vijf uur ophalen.","I will pick you up at five.",1],
["rits","zipper","De rits van mijn jas is kapot.","The zipper of my coat is broken.",1],
["rugtas","backpack","Mijn boeken zitten in de rugtas.","My books are in the backpack.",1],
["bril","glasses","Zonder mijn bril zie ik slecht.","Without my glasses I cannot see well.",1],
["portemonnee","wallet","Mijn portemonnee is leeg.","My wallet is empty.",1],
["boek","book","Dit boek is interessant.","This book is interesting.",1],
["lunch","lunch","Wat eet je voor de lunch?","What do you eat for lunch?",1],
["sportkleding","sport clothes","Doe je sportkleding aan.","Put on your sports clothes.",1],
["brood","bread","Ik eet brood met kaas.","I eat bread with cheese.",1],
["zelf","yourself","Heb je dit zelf gemaakt?","Did you make this yourself?",1],
["kinderen","children","De kinderen spelen in de tuin.","The children play in the garden.",1],
["meedoen","participate","Wil je meedoen met het spel?","Do you want to participate in the game?",1],
["bruiloft","wedding","We zijn naar een bruiloft geweest.","We went to a wedding.",1],
["opgeven","register","Geef je op voor de cursus.","Register for the course.",1],
["cadeaubon","gift card","Ik geef een cadeaubon.","I am giving a gift card.",1],
["kiezen","choose/select","Je mag zelf kiezen.","You may choose yourself.",1],
["geld","money","Ik heb geen geld bij me.","I have no money with me.",1],
["gekozen/kiezen","(past) chosen / choose","Ik heb voor het rode jasje gekozen.","I have chosen the red jacket.",1],
["cadeau","gift/present","Ik heb een cadeau voor jou.","I have a present for you.",1],
["meest","most","Dit is het meest gekochte boek.","This is the most bought book.",1],
["verrassing","surprise","Ik heb een verrassing voor jou.","I have a surprise for you.",1],
["vooral","especially","Ik hou vooral van koffie.","I especially like coffee.",1],
["feestcommissie","party committee","De feestcommissie regelt alles.","The party committee arranges everything.",1],
["taak","task","Dit is mijn taak voor vandaag.","This is my task for today.",1],
["geregeld","arranged","Alles is geregeld.","Everything is arranged.",1],
["EHBO","first aid","Ik heb een EHBO-cursus gevolgd.","I took a first-aid course.",1],
["basisschool/lagere school","primary school","Mijn dochter zit op de basisschool.","My daughter is in primary school.",1],
["meest geschikt","most appropriate","Dit is het meest geschikte plan.","This is the most appropriate plan.",1],
["ouders","parents","Mijn ouders wonen in Spanje.","My parents live in Spain.",1],
["verzorgers","caretakers","De verzorgers werken in een huis.","The caretakers work in a home.",1],
["reanimeren","reanimate","Hij kan reanimeren.","He can resuscitate.",1],
["bijeenkomsten","meetings","Er zijn maandelijkse bijeenkomsten.","There are monthly meetings.",1],
["hoeveel","how many/much","Hoeveel kost dit?","How much does this cost?",1],
["bestaat uit","consists of","Het team bestaat uit vijf personen.","The team consists of five people.",1],
["zoveel mogelijk","as much as possible","Eet zoveel mogelijk groente.","Eat as much vegetables as possible.",1],
["weggooien","throw away","Je moet dit weggooien.","You should throw this away.",1],
["repareren","repair","Ik laat mijn fiets repareren.","I am having my bike repaired.",1],
["maken","make","Ik ga eten maken.","I am going to make food.",1],
["terugbrengen","bring back","Ik moet het boek terugbrengen.","I have to bring the book back.",1],
["eigenaar","owner","Wie is de eigenaar van deze auto?","Who is the owner of this car?",1],
["gebruikte spullen","used stuff","We verkopen gebruikte spullen.","We sell used stuff.",1],
["regelmatig","regular","Ik sport regelmatig.","I exercise regularly.",1],
["spullen/dingen","stuff","Pak je spullen bij elkaar.","Get your stuff together.",1],
["kapot/stuk","broken","De stoel is kapot.","The chair is broken.",1],
["controleren","check","Ik controleer het werk.","I check the work.",1],
["proberen","try","Wil je het proberen?","Do you want to try it?",1],
["verkopen","sell","We willen ons huis verkopen.","We want to sell our house.",1],
["gratis","free","De koffie is gratis.","The coffee is free.",1],
["niets","nothing","Ik weet er niets van.","I know nothing about it.",1],
["goede doelen","charity","Het geld gaat naar goede doelen.","The money goes to charity.",1],
["medewerkers","employees","De medewerkers zijn aardig.","The employees are nice.",1],
["naartoe","to (a place)","Waar gaan we naartoe?","Where are we going to?",1],
["kinderboerderij","children's farm","We gaan naar de kinderboerderij.","We are going to the children's farm.",1],
["vrijwilligers","volunteers","De vrijwilligers helpen graag.","The volunteers like to help.",1],
["verdienen","earn","Hij verdient goed geld.","He earns good money.",1],

// --- Mock 2 ---
["kiespijn","toothache","Ik heb kiespijn.","I have a toothache.",2],
["zo snel mogelijk","as soon as possible","Kom zo snel mogelijk.","Come as soon as possible.",2],
["receptie","reception","Meld je bij de receptie.","Report at the reception.",2],
["nood nummer","emergency number","Bel het noodnummer.","Call the emergency number.",2],
["praktijk","practice","De praktijk is in de stad.","The practice is in the city.",2],
["Kindertandarts","child dentist","Mijn zoon gaat naar de kindertandarts.","My son goes to the child dentist.",2],
["geopend","open","De winkel is geopend.","The shop is open.",2],
["gesloten","closed","Het museum is gesloten.","The museum is closed.",2],
["spoed","emergency","Dit is een spoedgeval.","This is an emergency.",2],
["afspraak","appointment","Ik heb een afspraak om drie uur.","I have an appointment at three.",2],
["cv","resume","Stuur je cv naar dit adres.","Send your resume to this address.",2],
["vacature","vacancy","Er is een nieuwe vacature.","There is a new vacancy.",2],
["een baan","job","Ik zoek een baan.","I am looking for a job.",2],
["buurthuis","community center","Het buurthuis organiseert feesten.","The community centre organizes parties.",2],
["werkervaring","work experience","Ik heb veel werkervaring.","I have a lot of work experience.",2],
["persoonlijke gegevens","personal details","Vul je persoonlijke gegevens in.","Fill in your personal details.",2],
["overig","additional","Voor overige vragen kun je bellen.","For additional questions you can call.",2],
["vrijwillig","voluntarily","Ik werk vrijwillig in het buurthuis.","I work voluntarily in the community centre.",2],
["zetten","put","Zet je tas op de tafel.","Put your bag on the table.",2],
["rijbewijs","driver's license","Heb je een rijbewijs?","Do you have a driver's license?",2],
["scooter","scooter","Ik ga met de scooter.","I am going by scooter.",2],
["buitenland","abroad","Ik ga naar het buitenland.","I am going abroad.",2],
["schriftelijk","written","Geef het antwoord schriftelijk.","Give the answer in writing.",2],
["buiten","outside","We eten buiten op het terras.","We eat outside on the terrace.",2],
["uiterlijk","at the latest","Stuur het uiterlijk maandag.","Send it at the latest on Monday.",2],
["open dag","open day","Er is een open dag op zaterdag.","There is an open day on Saturday.",2],
["tijdens","during","Tijdens de les is praten niet toegestaan.","During the class, talking is not allowed.",2],
["kunnen","can","Wij kunnen je helpen.","We can help you.",2],
["helpen","help","Kan ik je helpen?","Can I help you?",2],
["openingstijden","opening times","Wat zijn de openingstijden?","What are the opening times?",2],
["ziek melden","report ill","Ik moet me ziek melden.","I have to report sick.",2],
["leidinggevende","supervisor","Bespreek het met je leidinggevende.","Discuss it with your supervisor.",2],
["secretariaat","secretary's office","Bel het secretariaat.","Call the secretary's office.",2],
["bereiken","reach","Hoe kan ik je bereiken?","How can I reach you?",2],
["bereikbaar","reachable","Ik ben de hele dag bereikbaar.","I am reachable all day.",2],
["bedrijfsarts","company doctor","De bedrijfsarts komt langs.","The company doctor is visiting.",2],
["altijd","always","Ik drink altijd koffie.","I always drink coffee.",2],
["op elk moment","at any moment","Bel me op elk moment.","Call me at any moment.",2],
["uitnodiging","invitation","Ik heb een uitnodiging gekregen.","I received an invitation.",2],
["buurtbijeenkomst","community meeting","Ga je naar de buurtbijeenkomst?","Are you going to the community meeting?",2],
["veranderingen","changes","Er zijn veel veranderingen.","There are many changes.",2],
["bespreken","discuss","We moeten dit plan bespreken.","We need to discuss this plan.",2],
["ontvangst","welcome/reception","Hartelijk welkom bij de ontvangst.","Warm welcome at the reception.",2],
["muzikaal","musical","Ze is heel muzikaal.","She is very musical.",2],
["optreden","performance","Er is een optreden vanavond.","There is a performance tonight.",2],
["thema","theme","Het thema van het feest is zomer.","The theme of the party is summer.",2],
["hapjes","bites/snacks","Er zijn hapjes en drankjes.","There are snacks and drinks.",2],
["drankjes","drinks","Wil je iets drinken?","Do you want a drink?",2],
["muziek","music","Ik luister naar muziek.","I listen to music.",2],
["activiteiten","activities","Er zijn veel activiteiten.","There are many activities.",2],
["abonnement","subscription","Ik heb een abonnement op de krant.","I have a subscription to the newspaper.",2],
["basis","base","Op basis hiervan kiezen we.","Based on this we choose.",2],
["werkdagen","workdays","Maandag tot vrijdag zijn werkdagen.","Monday to Friday are workdays.",2],
["weekend","weekend","In het weekend ben ik vrij.","In the weekend I am free.",2],
["bedanken","thank","Ik wil je bedanken.","I want to thank you.",2],
["gebruiken","use","Mag ik je pen gebruiken?","May I use your pen?",2],
["durven","dare","Ik durf het niet.","I do not dare.",2],
["beter","better","Dit is beter dan dat.","This is better than that.",2],
["nooit","never","Ik drink nooit alcohol.","I never drink alcohol.",2],
["moeilijk","difficult","Het is een moeilijke vraag.","It is a difficult question.",2],
["makkelijk","easy","Dit is heel makkelijk.","This is very easy.",2],
["fouten","mistakes","Iedereen maakt fouten.","Everyone makes mistakes.",2],
["geholpen/helpen","(past) helped / help","Hij heeft mij geholpen.","He has helped me.",2],
["zonder","without","Ik kom zonder mijn man.","I am coming without my husband.",2],
["anderen","others","Help de anderen.","Help the others.",2],
["taal","language","Nederlands is een mooie taal.","Dutch is a beautiful language.",2],
["echt","for real/really","Is dat echt waar?","Is that really true?",2],
["het is jammer","it's a pity","Het is jammer dat je niet komt.","It is a pity that you are not coming.",2],
["te lang","too long","Het duurt te lang.","It takes too long.",2],
["te weinig","not enough","Ik heb te weinig tijd.","I have not enough time.",2],
["afgemaakt","finished","Ik heb mijn werk afgemaakt.","I have finished my work.",2],
["geslaagd","passed (exam)","Ik ben geslaagd voor het examen.","I passed the exam.",2],
["weinig","not a lot","Ik heb weinig geld.","I have not a lot of money.",2],
["telefonisch spreekuur","telephone hours","Het telefonisch spreekuur is van negen tot tien.","Telephone hours are from nine to ten.",2],
["vakantie","holidays","Ik ga in juli op vakantie.","I am going on holiday in July.",2],
["schuiven","slide","Schuif de stoel naar links.","Slide the chair to the left.",2],
["volgorde","sequence/order","Zet de boeken op volgorde.","Put the books in order.",2],
["boven","up/upstairs","Mijn slaapkamer is boven.","My bedroom is upstairs.",2],
["beneden","down/downstairs","Kom even beneden.","Come down for a moment.",2],
["door elkaar","mixed up","Alles ligt door elkaar.","Everything is mixed up.",2],
["niet alleen","not only","Niet alleen ik, maar ook zij.","Not only me, but also her.",2],
["moeite","trouble/effort","Ik heb moeite met Nederlands.","I have trouble with Dutch.",2],
["sommige","some","Sommige mensen houden van regen.","Some people like rain.",2],
["hoe lang","how long","Hoe lang ben je hier al?","How long have you been here?",2],
["ruilen","swap/exchange","Kan ik dit ruilen?","Can I swap this?",2],
["eerste","first","Dit is mijn eerste keer.","This is my first time.",2],
["klantenkaart","customer card","Heeft u een klantenkaart?","Do you have a customer card?",2],
["nieuw","new","Ik heb een nieuwe telefoon.","I have a new phone.",2],
["dweilen","mop the floor","Ik moet de vloer dweilen.","I have to mop the floor.",2],
["deden","did (past of doen)","Wat deden jullie gisteren?","What did you do yesterday?",2],
["1 keer","one time","Ik ben maar 1 keer geweest.","I have only been once.",2],
["vies","dirty","De keuken is vies.","The kitchen is dirty.",2],
["derde","third","Dit is de derde keer.","This is the third time.",2],

// --- Mock 3 ---
["leeftijd","age","Wat is je leeftijd?","What is your age?",3],
["laatste","last","Dit is mijn laatste les.","This is my last lesson.",3],
["verkopers","salespeople","De verkopers zijn vriendelijk.","The salespeople are friendly.",3],
["stoppen","stop","Ik moet stoppen met roken.","I have to stop smoking.",3],
["bijzonder","special","Dit is een bijzondere dag.","This is a special day.",3],
["feest","party","Het feest begint om acht uur.","The party starts at eight.",3],
["kantine","canteen","We eten in de kantine.","We eat in the canteen.",3],
["afscheid nemen","say goodbye","We nemen afscheid van onze collega.","We say goodbye to our colleague.",3],
["gezellig","cozy","Het is gezellig bij jullie thuis.","It is cozy at your house.",3],
["straks","later","Ik zie je straks.","I will see you later.",3],
["druk","busy","Het is hier erg druk.","It is very busy here.",3],
["genoeg","enough","Ik heb genoeg gegeten.","I have eaten enough.",3],
["blijven","stay","Ik blijf vanavond thuis.","I am staying home tonight.",3],
["schoon","clean","Het huis is schoon.","The house is clean.",3],
["waarom","why","Waarom ben je laat?","Why are you late?",3],
["minder","less","Ik eet minder suiker.","I eat less sugar.",3],
["vaker","more often","We moeten elkaar vaker zien.","We should see each other more often.",3],
["hoe vaak","how often","Hoe vaak ga je sporten?","How often do you exercise?",3],
["vertrekken","leave","We vertrekken om zes uur.","We are leaving at six o'clock.",3],
["overdag","during the day","Overdag werk ik op kantoor.","During the day I work at the office.",3],
["'s avonds","in the evening","'s Avonds kijk ik tv.","In the evening I watch TV.",3],
["vergadering","meeting","De vergadering begint om tien uur.","The meeting starts at ten.",3],
["buurt","neighbourhood","Ik woon in een rustige buurt.","I live in a quiet neighbourhood.",3],
["afspreken","make an appointment/meet","Zullen we morgen afspreken?","Shall we meet tomorrow?",3],
["activiteit","activity","Welke activiteit kies je?","Which activity do you choose?",3],
["buurbewoners","residents/neighbours","De buurbewoners helpen elkaar.","The neighbours help each other.",3],
["kosten","costs","Wat zijn de kosten?","What are the costs?",3],
["uitrekenen","calculate","Ik moet de prijs uitrekenen.","I have to calculate the price.",3],
["duurder","more expensive","Dit is duurder dan ik dacht.","This is more expensive than I thought.",3],
["sturen","send","Ik ga je een mail sturen.","I am going to send you an email.",3],
["moeten","must","Ik moet nu naar huis.","I must go home now.",3],
["iedereen","everybody","Iedereen is welkom.","Everybody is welcome.",3],
["vinden","opinion/think","Wat vind je van het plan?","What is your opinion of the plan?",3],
["opsturen","send","Kun je mij de foto opsturen?","Can you send me the photo?",3],
["toen","then/when (past)","Toen ik klein was, woonde ik hier.","When I was small, I lived here.",3],
["spelletjes","games","We spelen spelletjes op het feest.","We play games at the party.",3],
["pannenkoeken","pancakes","We eten pannenkoeken met stroop.","We eat pancakes with syrup.",3],
["hoe duur","how expensive","Hoe duur is dit boek?","How expensive is this book?",3],
["vorig jaar","last year","Vorig jaar ben ik verhuisd.","Last year I moved.",3],
["groeien","grow/expand","De plant groeit snel.","The plant grows fast.",3],
["bekend","famous","Hij is een bekend schrijver.","He is a famous writer.",3],
["vriendelijk","friendly/kind","De buurman is heel vriendelijk.","The neighbour is very friendly.",3],
["tevreden","satisfied","Ik ben tevreden met mijn werk.","I am satisfied with my work.",3],
["doordeweeks","throughout the week","Doordeweeks werk ik veel.","Throughout the week I work a lot.",3],
["ervaring","experience","Ik heb veel ervaring met koken.","I have a lot of experience cooking.",3],
["voordeel","advantage","Dit heeft een groot voordeel.","This has a big advantage.",3],
["nadeel","disadvantage","Het nadeel is dat het duur is.","The disadvantage is that it is expensive.",3],
["omgaan met","to handle","Ik kan goed omgaan met kinderen.","I am good at handling children.",3],
["beschikbaar","available","Ik ben morgen beschikbaar.","I am available tomorrow.",3],
["eerder","earlier","Kom eerder als je wilt.","Come earlier if you want.",3],
["plekken","places","Er zijn nog twee plekken vrij.","There are still two places free.",3],
["geschiedenis","history","Ik hou van geschiedenis.","I love history.",3],
["vertellen","tell","Kun je het verhaal vertellen?","Can you tell the story?",3],
["oefenen","practice","Ik moet meer Nederlands oefenen.","I have to practice Dutch more.",3],
["bezoek","visitors","We krijgen vandaag bezoek.","We are having visitors today.",3],
["gisteren","yesterday","Gisteren was het mooi weer.","Yesterday the weather was nice.",3],
["samen","together","We koken samen het eten.","We cook the food together.",3],
["zoeken","looking for/search","Ik zoek mijn sleutels.","I am looking for my keys.",3],
["winkels","shops","De winkels gaan om negen uur open.","The shops open at nine.",3],
["daarover","about that","Daarover wil ik graag praten.","I would like to talk about that.",3],
["informatie","information","Ik heb meer informatie nodig.","I need more information.",3],
["werkrooster","work schedule","Mijn werkrooster verandert.","My work schedule is changing.",3],
["probleem","problem","Ik heb een probleem met mijn computer.","I have a problem with my computer.",3],
["gebroken","broken","Mijn telefoon is gebroken.","My phone is broken.",3],
["laten weten","let know","Laat me even weten of je komt.","Let me know if you are coming.",3],
["gereedschap","tools","Ik heb gereedschap nodig.","I need tools.",3],
["theorieboek","theory book","Ik leer uit het theorieboek.","I study from the theory book.",3],
["bestellen","order","Ik wil een pizza bestellen.","I want to order a pizza.",3],
["soorten","types/varieties","Er zijn veel soorten kaas.","There are many varieties of cheese.",3],
["meubel","furniture","Dit meubel is van hout.","This piece of furniture is made of wood.",3],
["ontwerpen","design","Hij gaat een huis ontwerpen.","He is going to design a house.",3],
["inschrijven","register","Je moet je voor de cursus inschrijven.","You must register for the course.",3],
["het enige","the only thing","Dat is het enige wat ik wil.","That is the only thing I want.",3],
["hout","wood","De tafel is van hout.","The table is made of wood.",3],
["daarmee","with that","Daarmee ben ik klaar.","I am done with that.",3],
["op tijd","on time","Kom op tijd voor de les.","Come on time for the lesson.",3],
["afmelden","log out/unregister","Ik moet me afmelden voor de cursus.","I have to log out of the course.",3],
["verhuizen","move (house)","We gaan volgende maand verhuizen.","We are going to move next month.",3],
["tandarts","dentist","Ik ga naar de tandarts.","I am going to the dentist.",3],
["helaas","unfortunately","Helaas kan ik niet komen.","Unfortunately I cannot come.",3],
["verplaatst","rescheduled","De vergadering is verplaatst.","The meeting has been rescheduled.",3],
["hetzelfde","same","Ik bestel hetzelfde als jij.","I will order the same as you.",3],
["voldoende","enough","Ik heb voldoende geld.","I have enough money.",3],
["namelijk","namely","Ik ben moe, namelijk omdat ik laat sliep.","I am tired, namely because I slept late.",3],
["vakantierooster","holiday schedule","Het vakantierooster is klaar.","The holiday schedule is ready.",3],
["aanvragen","apply for","Ik wil verlof aanvragen.","I want to apply for leave.",3],
["aan het werk","at work","Ik ben aan het werk.","I am at work.",3],
["balie","desk/counter","Meld je bij de balie.","Report at the desk.",3],
["nodig","needed","Ik heb hulp nodig.","I need help.",3],
["telefoon opnemen","answer the phone","Kun je de telefoon opnemen?","Can you answer the phone?",3],
["achter elkaar","in a row","Drie dagen achter elkaar gewerkt.","Worked three days in a row.",3],

// --- Mock 4 ---
["weten","to know","Ik weet het antwoord niet.","I do not know the answer.",4],
["kennis","knowledge","Hij heeft veel kennis over geschiedenis.","He has a lot of knowledge about history.",4],
["reden","reason","Wat is de reden van je bezoek?","What is the reason for your visit?",4],
["praten","talk","We praten elke dag met elkaar.","We talk to each other every day.",4],
["studeren","study","Ik ga vanavond studeren voor de toets.","I am going to study for the test tonight.",4],
["werken","work","Mijn vader werkt in een ziekenhuis.","My father works in a hospital.",4],
["dicht","closed","De winkel is vandaag dicht.","The shop is closed today.",4],
["taken","tasks","Ik heb veel taken op het werk.","I have many tasks at work.",4],
["veranderen","change","Ik wil mijn baan veranderen.","I want to change my job.",4],
["winkel","shop","De winkel opent om negen uur.","The shop opens at nine o'clock.",4],
["volgende week","next week","Volgende week ga ik op vakantie.","Next week I am going on holiday.",4],
["horen","hear","Ik kan je niet goed horen.","I cannot hear you well.",4],
["maand","month","Deze maand is heel druk.","This month is very busy.",4],
["tot","until","De winkel is open tot zes uur.","The shop is open until six o'clock.",4],
["mensen","people","Er zijn veel mensen in de stad.","There are many people in the city.",4],
["rooster","schedule","Mijn rooster verandert elke week.","My schedule changes every week.",4],
["natuurlijk","of course","Natuurlijk help ik je graag.","Of course I am happy to help you.",4],
["allemaal","all","We gaan allemaal naar het feest.","We are all going to the party.",4],
["misschien","maybe","Misschien regent het morgen.","Maybe it will rain tomorrow.",4],
["volgende maand","next month","Volgende maand ben ik jarig.","Next month is my birthday.",4],
["iedere","every","Iedere ochtend drink ik koffie.","Every morning I drink coffee.",4],
["langer","longer","Hij blijft langer dan verwacht.","He stays longer than expected.",4],
["willen","want","Ik wil een nieuwe fiets.","I want a new bicycle.",4],
["omdat","because","Ik blijf thuis omdat ik ziek ben.","I stay home because I am sick.",4],
["werktijden","working times","Mijn werktijden zijn van negen tot vijf.","My working times are from nine to five.",4],
["cursus","course","Ik volg een cursus Nederlands.","I am taking a Dutch course.",4],
["repareren/maken","fix/make","Kun je mijn fiets repareren?","Can you fix my bicycle?",4],
["baan","job","Ze zoekt een nieuwe baan.","She is looking for a new job.",4],
["opleiding","education/training","Welke opleiding heb je gedaan?","Which education did you do?",4],
["van tevoren","in advance","Bel even van tevoren.","Call in advance please.",4],
["folder","brochure","Hier is een folder met informatie.","Here is a brochure with information.",4],
["overzicht/schema","overview/schedule","Ik heb een overzicht gemaakt.","I made an overview.",4],
["verschillende/diverse","various","Er zijn verschillende kleuren.","There are various colors.",4],
["waar","where","Waar woon jij?","Where do you live?",4],
["bellen","call","Ik ga mijn moeder bellen.","I am going to call my mother.",4],
["normaal","normal","Normaal sta ik om zeven uur op.","Normally I get up at seven.",4],
["andere","other","Ik wil de andere kleur.","I want the other color.",4],
["dicht/gesloten","closed","Het museum is vandaag gesloten.","The museum is closed today.",4],
["de weg","the road/way","Ik weet de weg niet.","I do not know the road/way.",4],
["bushalte","bus stop","De bushalte is om de hoek.","The bus stop is around the corner.",4],
["opstappen","get on the bus","Waar moet ik opstappen?","Where should I get on the bus?",4],
["gemeente","municipality","Ik moet naar de gemeente.","I have to go to the municipality.",4],
["mogen","may","Mag ik even langskomen?","May I come by for a moment?",4],
["kermis","fair","De kermis is in de stad.","The fair is in town.",4],
["gebouw","building","Dat gebouw is heel oud.","That building is very old.",4],
["studiecentrum","study centre","Ik leer in het studiecentrum.","I study at the study centre.",4],
["lokaal","classroom","Het lokaal is op de tweede verdieping.","The classroom is on the second floor.",4],
["begane grond","ground floor","De receptie is op de begane grond.","The reception is on the ground floor.",4],
["vanaf","from","Vanaf maandag begin ik te werken.","From Monday I start working.",4],
["weer","again","Tot ziens, tot de volgende keer weer!","Goodbye, see you again next time!",4],
["verbouwing","renovation","Het huis is in verbouwing.","The house is under renovation.",4],
["doorgaan","take place/continue","De les gaat vandaag door.","The class takes place today.",4],
["overslaan","skip","Ik wil het ontbijt overslaan.","I want to skip breakfast.",4],
["de regels","the rules","Volg de regels van het spel.","Follow the rules of the game.",4],
["klanten","customers","De winkel heeft veel klanten.","The shop has many customers.",4],
["stofzuigen","vacuum (clean)","Ik ga de kamer stofzuigen.","I am going to vacuum the room.",4],
["speelgoed","toys","De kinderen ruimen het speelgoed op.","The children tidy up the toys.",4],
["stil zitten","sit still","Kinderen kunnen niet lang stil zitten.","Children cannot sit still for long.",4],
["netjes","decent/neat","Hij ziet er netjes uit.","He looks decent/neat.",4],
["schoonmaken","clean","Ik ga het huis schoonmaken.","I am going to clean the house.",4],
["alleen","only/alone","Ik woon alleen.","I live alone.",4],
["opletten","pay attention","Let goed op in de les.","Pay attention in class.",4],
["fijn","fine/nice","Wat een fijne dag!","What a fine day!",4],
["elkaar","each other","We helpen elkaar.","We help each other.",4],
["te veel","too much","Dit is te veel werk.","This is too much work.",4],
["maar","but","Ik wil komen, maar ik kan niet.","I want to come, but I cannot.",4],
["inhalen","catch up","Ik moet de les inhalen.","I have to catch up the lesson.",4],
["missen","miss","Ik mis mijn familie.","I miss my family.",4],
["vervelend","annoying","Wat vervelend voor je.","How annoying for you.",4],
["toets","test","Morgen heb ik een toets.","Tomorrow I have a test.",4],
["woordenboek","dictionary","Ik zoek het woord in het woordenboek.","I look up the word in the dictionary.",4],
["slim","smart","Mijn zoon is heel slim.","My son is very smart.",4],
["opdrachten","assignments","De opdrachten zijn moeilijk.","The assignments are difficult.",4],
["trouwens","by the way","Trouwens, hoe gaat het met je moeder?","By the way, how is your mother?",4],
["foto's","pictures","Ik laat je de foto's zien.","I will show you the pictures.",4],
["knipbeurt","haircut","Ik heb een knipbeurt nodig.","I need a haircut.",4],
["een afspraak maken","make an appointment","Ik wil een afspraak maken.","I want to make an appointment.",4],
["nieuwsbrief","newsletter","De nieuwsbrief komt elke maand.","The newsletter comes every month.",4],
["dochtertje","little daughter","Haar dochtertje is drie jaar oud.","Her little daughter is three years old.",4],
["wassen","wash","Ik moet mijn handen wassen.","I have to wash my hands.",4],
["knippen","cut","Mag ik mijn haar laten knippen?","May I have my hair cut?",4],
["vieren","celebrate","We vieren mijn verjaardag.","We celebrate my birthday.",4],
["getrouwd","married","Mijn zus is getrouwd.","My sister is married.",4],
["zwembad","swimming pool","We gaan naar het zwembad.","We are going to the swimming pool.",4],
["lied","song","Ik ken dat lied.","I know that song.",4],
["ik heb geen idee","I have no idea","Ik heb geen idee waar hij is.","I have no idea where he is.",4],
["dat weet ze niet","she doesn't know that","Vraag het haar, dat weet ze niet.","Ask her, she doesn't know.",4],
["feestdagen","holidays (festive)","Tijdens de feestdagen zijn we thuis.","During the holidays we are at home.",4],
["de rest","the remaining part","De rest doe ik morgen.","The remaining part I will do tomorrow.",4],
["afdeling","department","Welke afdeling zoekt u?","Which department are you looking for?",4],
["de reden","the reason","De reden is dat ik ziek ben.","The reason is that I am sick.",4],
["simpel","simple","Het is heel simpel.","It is very simple.",4],
];
