// Raw vocabulary pulled from the four flashcard decks.
// Fields: [dutch, english, dutchSentence, englishSentence, deck, breakdown?]
const RAW_CARDS = [
// --- Mock 1 ---
["rustig","quiet","De buurt is heel rustig.","The neighbourhood is very quiet.",1],
["plek/plaats","place","Is hier nog een plek vrij?","Is there a place free here?",1],
["nadenken","think hard","Ik moet even nadenken.","I have to think for a moment.",1,"na (after) + denken (think)"],
["inhoud","contents","De inhoud van het boek is goed.","The contents of the book are good.",1,"in (in) + houden (hold)"],
["planning","planning","Wat is je planning voor vandaag?","What is your planning for today?",1],
["manier","way","Op deze manier werkt het beter.","This way it works better.",1],
["beginnen","start","De les begint om tien uur.","The class starts at ten o'clock.",1],
["verschillende","various","Er zijn verschillende kleuren.","There are various colors.",1],
["bladzijde/pagina","page","Op welke bladzijde staan we?","What page are we on?",1,"blad (leaf) + zijde (side)"],
["opnieuw","again and again","Probeer het opnieuw.","Try it again.",1,"op (on) + nieuw (new)"],
["onthouden","remember","Kun je dit onthouden?","Can you remember this?",1,"ont- + houden (hold) → hold onto"],
["uitzoeken","find out","Ik moet dit uitzoeken.","I have to find this out.",1,"uit (out) + zoeken (search)"],
["pauze","break","We hebben een korte pauze.","We have a short break.",1],
["omgeving","environment","De omgeving is mooi.","The environment is beautiful.",1,"om (around) + geven (give) → surround"],
["uitleggen","explain","Kun je dit uitleggen?","Can you explain this?",1,"uit (out) + leggen (lay) → lay out"],
["tekst","text","Lees deze tekst.","Read this text.",1],
["belangrijk","important","Dit is heel belangrijk.","This is very important.",1,"belang (interest) + rijk (rich in)"],
["het eerste","first","Dit is het eerste boek.","This is the first book.",1],
["bepalen/besluiten","decide","Je moet zelf besluiten.","You have to decide yourself.",1,"besluiten: be- + sluiten (to close)"],
["wanneer","when","Wanneer kom je thuis?","When are you coming home?",1],
["of","or","Wil je thee of koffie?","Do you want tea or coffee?",1],
["een beetje","little bit","Ik spreek een beetje Nederlands.","I speak a little bit of Dutch.",1],
["neem","take","Neem een stoel.","Take a chair.",1],
["dorpsbewoner","village residents","De dorpsbewoners kennen elkaar.","The village residents know each other.",1,"dorp (village) + bewoner (resident, from wonen 'live')"],
["rondom","around","Rondom het huis staan bomen.","Around the house there are trees.",1,"rond (round) + om (around)"],
["oproepen","a call","Hij krijgt een oproep van de dokter.","He gets a call from the doctor.",1,"op (up) + roepen (call)"],
["jaarlijkse","yearly","Dit is de jaarlijkse vergadering.","This is the yearly meeting.",1,"jaar (year) + -lijk (-ly)"],
["weghalen","remove","Kun je dit weghalen?","Can you remove this?",1,"weg (away) + halen (get)"],
["wegslepen","tow away","Ze willen mijn auto wegslepen.","They want to tow my car away.",1,"weg (away) + slepen (drag)"],
["daarom","that's why","Het regent, daarom blijf ik thuis.","It is raining, that's why I stay home.",1,"daar (there) + om (for)"],
["verdieping/etage","floor","Ik woon op de derde verdieping.","I live on the third floor.",1,"diep (deep) + -ing (from verdiepen 'deepen')"],
["gekocht/kopen","(past) bought / buy","Ik heb een nieuw boek gekocht.","I bought a new book.",1,"ge- (past participle) + kopen (buy)"],
["betalen","pay","Kan ik met pin betalen?","Can I pay by card?",1],
["bezorging","delivery","De bezorging is gratis.","The delivery is free.",1,"be- + zorgen (care for) + -ing"],
["levertijd","delivery time","Wat is de levertijd?","What is the delivery time?",1,"leveren (deliver) + tijd (time)"],
["klantenservice","customer service","Bel de klantenservice.","Call customer service.",1,"klant (customer) + service"],
["meenemen","take along","Vergeet je paraplu niet mee te nemen.","Do not forget to take your umbrella along.",1,"mee (along) + nemen (take)"],
["zwemkleding","swimming costume","Vergeet je zwemkleding niet.","Don't forget your swimming costume.",1,"zwemmen (swim) + kleding (clothing)"],
["handdoek","towel","Neem een schone handdoek mee.","Take a clean towel along.",1,"hand + doek (cloth)"],
["extra/meer","more","Wil je nog extra koffie?","Do you want extra coffee?",1],
["aanraden/adviseren","advise","Ik kan dit boek aanraden.","I can recommend this book.",1,"aan (to) + raden (advise/guess)"],
["meemogen","may join","Mag ik meegaan met de bus?","May I join on the bus?",1,"mee (along) + mogen (may)"],
["aanmelden","register","Je kunt je online aanmelden.","You can register online.",1,"aan (on) + melden (report)"],
["vragen","questions","Mag ik je iets vragen?","May I ask you something?",1],
["portier","porter","De portier staat bij de deur.","The porter stands at the door.",1],
["bureau","desk","Mijn bureau is opgeruimd.","My desk is tidy.",1],
["trein","train","De trein vertrekt om acht uur.","The train leaves at eight.",1],
["vergeten","forget","Ik ben mijn sleutels vergeten.","I forgot my keys.",1],
["merken","notice","Ik merk dat je moe bent.","I notice that you are tired.",1],
["ophalen","pick up","Ik kom je om vijf uur ophalen.","I will pick you up at five.",1,"op (up) + halen (fetch)"],
["rits","zipper","De rits van mijn jas is kapot.","The zipper of my coat is broken.",1],
["rugtas","backpack","Mijn boeken zitten in de rugtas.","My books are in the backpack.",1,"rug (back) + tas (bag)"],
["bril","glasses","Zonder mijn bril zie ik slecht.","Without my glasses I cannot see well.",1],
["portemonnee","wallet","Mijn portemonnee is leeg.","My wallet is empty.",1],
["boek","book","Dit boek is interessant.","This book is interesting.",1],
["lunch","lunch","Wat eet je voor de lunch?","What do you eat for lunch?",1],
["sportkleding","sport clothes","Doe je sportkleding aan.","Put on your sports clothes.",1,"sport + kleding (clothing)"],
["brood","bread","Ik eet brood met kaas.","I eat bread with cheese.",1],
["zelf","yourself","Heb je dit zelf gemaakt?","Did you make this yourself?",1],
["kinderen","children","De kinderen spelen in de tuin.","The children play in the garden.",1],
["meedoen","participate","Wil je meedoen met het spel?","Do you want to participate in the game?",1,"mee (along) + doen (do)"],
["bruiloft","wedding","We zijn naar een bruiloft geweest.","We went to a wedding.",1],
["opgeven","register","Geef je op voor de cursus.","Register for the course.",1,"op (up) + geven (give)"],
["cadeaubon","gift card","Ik geef een cadeaubon.","I am giving a gift card.",1,"cadeau (gift) + bon (voucher)"],
["kiezen","choose/select","Je mag zelf kiezen.","You may choose yourself.",1],
["geld","money","Ik heb geen geld bij me.","I have no money with me.",1],
["gekozen/kiezen","(past) chosen / choose","Ik heb voor het rode jasje gekozen.","I have chosen the red jacket.",1,"ge- (past participle) + kiezen (choose)"],
["cadeau","gift/present","Ik heb een cadeau voor jou.","I have a present for you.",1],
["meest","most","Dit is het meest gekochte boek.","This is the most bought book.",1],
["verrassing","surprise","Ik heb een verrassing voor jou.","I have a surprise for you.",1,"verrassen (to surprise) + -ing"],
["vooral","especially","Ik hou vooral van koffie.","I especially like coffee.",1,"voor (most) + al (all)"],
["feestcommissie","party committee","De feestcommissie regelt alles.","The party committee arranges everything.",1,"feest (party) + commissie (committee)"],
["taak","task","Dit is mijn taak voor vandaag.","This is my task for today.",1],
["geregeld","arranged","Alles is geregeld.","Everything is arranged.",1,"ge- + regelen (arrange)"],
["EHBO","first aid","Ik heb een EHBO-cursus gevolgd.","I took a first-aid course.",1,"acronym: Eerste Hulp Bij Ongelukken (first help with accidents)"],
["basisschool/lagere school","primary school","Mijn dochter zit op de basisschool.","My daughter is in primary school.",1,"basis (base) + school"],
["meest geschikt","most appropriate","Dit is het meest geschikte plan.","This is the most appropriate plan.",1,"meest (most) + geschikt (suitable)"],
["ouders","parents","Mijn ouders wonen in Spanje.","My parents live in Spain.",1],
["verzorgers","caretakers","De verzorgers werken in een huis.","The caretakers work in a home.",1,"verzorgen (care for, from zorg 'care') + -er"],
["reanimeren","reanimate","Hij kan reanimeren.","He can resuscitate.",1,"re- (again) + animeren (bring to life)"],
["bijeenkomsten","meetings","Er zijn maandelijkse bijeenkomsten.","There are monthly meetings.",1,"bijeen (together) + komst (from komen 'come')"],
["hoeveel","how many/much","Hoeveel kost dit?","How much does this cost?",1,"hoe (how) + veel (much)"],
["bestaat uit","consists of","Het team bestaat uit vijf personen.","The team consists of five people.",1,"bestaan (exist) + uit (out of)"],
["zoveel mogelijk","as much as possible","Eet zoveel mogelijk groente.","Eat as much vegetables as possible.",1,"zo (so) + veel (much) + mogelijk (possible)"],
["weggooien","throw away","Je moet dit weggooien.","You should throw this away.",1,"weg (away) + gooien (throw)"],
["repareren","repair","Ik laat mijn fiets repareren.","I am having my bike repaired.",1],
["maken","make","Ik ga eten maken.","I am going to make food.",1],
["terugbrengen","bring back","Ik moet het boek terugbrengen.","I have to bring the book back.",1,"terug (back) + brengen (bring)"],
["eigenaar","owner","Wie is de eigenaar van deze auto?","Who is the owner of this car?",1,"eigen (own) + -aar (-er)"],
["gebruikte spullen","used stuff","We verkopen gebruikte spullen.","We sell used stuff.",1,"gebruiken (to use) + spullen (stuff)"],
["regelmatig","regular","Ik sport regelmatig.","I exercise regularly.",1,"regel (rule) + -matig (-like)"],
["spullen/dingen","stuff","Pak je spullen bij elkaar.","Get your stuff together.",1],
["kapot/stuk","broken","De stoel is kapot.","The chair is broken.",1],
["controleren","check","Ik controleer het werk.","I check the work.",1],
["proberen","try","Wil je het proberen?","Do you want to try it?",1],
["verkopen","sell","We willen ons huis verkopen.","We want to sell our house.",1,"ver- + kopen (buy)"],
["gratis","free","De koffie is gratis.","The coffee is free.",1],
["niets","nothing","Ik weet er niets van.","I know nothing about it.",1,"niet (not) + iets (something)"],
["goede doelen","charity","Het geld gaat naar goede doelen.","The money goes to charity.",1,"goed (good) + doel (goal)"],
["medewerkers","employees","De medewerkers zijn aardig.","The employees are nice.",1,"mede- (co-) + werken (work) + -er"],
["naartoe","to (a place)","Waar gaan we naartoe?","Where are we going to?",1,"naar (to) + toe (towards)"],
["kinderboerderij","children's farm","We gaan naar de kinderboerderij.","We are going to the children's farm.",1,"kinderen (children) + boerderij (farm)"],
["vrijwilligers","volunteers","De vrijwilligers helpen graag.","The volunteers like to help.",1,"vrij (free) + willig (willing) + -er"],
["verdienen","earn","Hij verdient goed geld.","He earns good money.",1,"ver- + dienen (serve)"],

// --- Mock 2 ---
["kiespijn","toothache","Ik heb kiespijn.","I have a toothache.",2,"kies (molar) + pijn (pain)"],
["zo snel mogelijk","as soon as possible","Kom zo snel mogelijk.","Come as soon as possible.",2,"zo (so) + snel (fast) + mogelijk (possible)"],
["receptie","reception","Meld je bij de receptie.","Report at the reception.",2],
["nood nummer","emergency number","Bel het noodnummer.","Call the emergency number.",2,"nood (emergency) + nummer (number)"],
["praktijk","practice","De praktijk is in de stad.","The practice is in the city.",2],
["Kindertandarts","child dentist","Mijn zoon gaat naar de kindertandarts.","My son goes to the child dentist.",2,"kinder- (child) + tand (tooth) + arts (doctor)"],
["geopend","open","De winkel is geopend.","The shop is open.",2,"ge- + openen (to open)"],
["gesloten","closed","Het museum is gesloten.","The museum is closed.",2,"ge- + sluiten (close)"],
["spoed","emergency","Dit is een spoedgeval.","This is an emergency.",2],
["afspraak","appointment","Ik heb een afspraak om drie uur.","I have an appointment at three.",2,"af- + spreken (speak) → an agreement"],
["cv","resume","Stuur je cv naar dit adres.","Send your resume to this address.",2,"abbreviation of curriculum vitae"],
["vacature","vacancy","Er is een nieuwe vacature.","There is a new vacancy.",2],
["een baan","job","Ik zoek een baan.","I am looking for a job.",2],
["buurthuis","community center","Het buurthuis organiseert feesten.","The community centre organizes parties.",2,"buurt (neighbourhood) + huis (house)"],
["werkervaring","work experience","Ik heb veel werkervaring.","I have a lot of work experience.",2,"werk (work) + ervaring (experience)"],
["persoonlijke gegevens","personal details","Vul je persoonlijke gegevens in.","Fill in your personal details.",2,"persoon (person) + geven (give) → gegevens (data)"],
["overig","additional","Voor overige vragen kun je bellen.","For additional questions you can call.",2,"over (remaining) + -ig"],
["vrijwillig","voluntarily","Ik werk vrijwillig in het buurthuis.","I work voluntarily in the community centre.",2,"vrij (free) + willig (willing)"],
["zetten","put","Zet je tas op de tafel.","Put your bag on the table.",2],
["rijbewijs","driver's license","Heb je een rijbewijs?","Do you have a driver's license?",2,"rijden (drive) + bewijs (proof)"],
["scooter","scooter","Ik ga met de scooter.","I am going by scooter.",2],
["buitenland","abroad","Ik ga naar het buitenland.","I am going abroad.",2,"buiten (outside) + land (country)"],
["schriftelijk","written","Geef het antwoord schriftelijk.","Give the answer in writing.",2,"schrift (writing) + -elijk (-ly)"],
["buiten","outside","We eten buiten op het terras.","We eat outside on the terrace.",2],
["uiterlijk","at the latest","Stuur het uiterlijk maandag.","Send it at the latest on Monday.",2,"uit (out) + -er + -lijk → outermost, at latest"],
["open dag","open day","Er is een open dag op zaterdag.","There is an open day on Saturday.",2,"open + dag (day)"],
["tijdens","during","Tijdens de les is praten niet toegestaan.","During the class, talking is not allowed.",2,"tijd (time) + -ens"],
["kunnen","can","Wij kunnen je helpen.","We can help you.",2],
["helpen","help","Kan ik je helpen?","Can I help you?",2],
["openingstijden","opening times","Wat zijn de openingstijden?","What are the opening times?",2,"openen (to open) + tijden (times)"],
["ziek melden","report ill","Ik moet me ziek melden.","I have to report sick.",2,"ziek (sick) + melden (report)"],
["leidinggevende","supervisor","Bespreek het met je leidinggevende.","Discuss it with your supervisor.",2,"leiden (lead) + geven (give) → one who gives direction"],
["secretariaat","secretary's office","Bel het secretariaat.","Call the secretary's office.",2],
["bereiken","reach","Hoe kan ik je bereiken?","How can I reach you?",2,"be- + reiken (extend, reach)"],
["bereikbaar","reachable","Ik ben de hele dag bereikbaar.","I am reachable all day.",2,"bereiken (reach) + -baar (-able)"],
["bedrijfsarts","company doctor","De bedrijfsarts komt langs.","The company doctor is visiting.",2,"bedrijf (company) + arts (doctor)"],
["altijd","always","Ik drink altijd koffie.","I always drink coffee.",2,"al (all) + tijd (time)"],
["op elk moment","at any moment","Bel me op elk moment.","Call me at any moment.",2,"op (at) + elk (each) + moment"],
["uitnodiging","invitation","Ik heb een uitnodiging gekregen.","I received an invitation.",2,"uit (out) + nodigen (invite)"],
["buurtbijeenkomst","community meeting","Ga je naar de buurtbijeenkomst?","Are you going to the community meeting?",2,"buurt (neighbourhood) + bijeen (together) + komst (coming)"],
["veranderingen","changes","Er zijn veel veranderingen.","There are many changes.",2,"ver- + anderen (from ander 'other')"],
["bespreken","discuss","We moeten dit plan bespreken.","We need to discuss this plan.",2,"be- + spreken (speak)"],
["ontvangst","welcome/reception","Hartelijk welkom bij de ontvangst.","Warm welcome at the reception.",2,"ont- + vangen (catch/receive)"],
["muzikaal","musical","Ze is heel muzikaal.","She is very musical.",2],
["optreden","performance","Er is een optreden vanavond.","There is a performance tonight.",2,"op (up) + treden (step) → to perform"],
["thema","theme","Het thema van het feest is zomer.","The theme of the party is summer.",2],
["hapjes","bites/snacks","Er zijn hapjes en drankjes.","There are snacks and drinks.",2,"hap (bite) + -je (diminutive)"],
["drankjes","drinks","Wil je iets drinken?","Do you want a drink?",2,"drank (drink) + -je (diminutive)"],
["muziek","music","Ik luister naar muziek.","I listen to music.",2],
["activiteiten","activities","Er zijn veel activiteiten.","There are many activities.",2],
["abonnement","subscription","Ik heb een abonnement op de krant.","I have a subscription to the newspaper.",2],
["basis","base","Op basis hiervan kiezen we.","Based on this we choose.",2],
["werkdagen","workdays","Maandag tot vrijdag zijn werkdagen.","Monday to Friday are workdays.",2,"werk (work) + dagen (days)"],
["weekend","weekend","In het weekend ben ik vrij.","In the weekend I am free.",2],
["bedanken","thank","Ik wil je bedanken.","I want to thank you.",2,"be- + danken (thank, from dank 'thanks')"],
["gebruiken","use","Mag ik je pen gebruiken?","May I use your pen?",2],
["durven","dare","Ik durf het niet.","I do not dare.",2],
["beter","better","Dit is beter dan dat.","This is better than that.",2],
["nooit","never","Ik drink nooit alcohol.","I never drink alcohol.",2],
["moeilijk","difficult","Het is een moeilijke vraag.","It is a difficult question.",2,"moeite (trouble) + -lijk (-like)"],
["makkelijk","easy","Dit is heel makkelijk.","This is very easy.",2,"gemak (ease) + -kelijk (-like)"],
["fouten","mistakes","Iedereen maakt fouten.","Everyone makes mistakes.",2],
["geholpen/helpen","(past) helped / help","Hij heeft mij geholpen.","He has helped me.",2,"ge- + helpen (help)"],
["zonder","without","Ik kom zonder mijn man.","I am coming without my husband.",2],
["anderen","others","Help de anderen.","Help the others.",2],
["taal","language","Nederlands is een mooie taal.","Dutch is a beautiful language.",2],
["echt","for real/really","Is dat echt waar?","Is that really true?",2],
["het is jammer","it's a pity","Het is jammer dat je niet komt.","It is a pity that you are not coming.",2],
["te lang","too long","Het duurt te lang.","It takes too long.",2,"te (too) + lang (long)"],
["te weinig","not enough","Ik heb te weinig tijd.","I have not enough time.",2,"te (too) + weinig (little)"],
["afgemaakt","finished","Ik heb mijn werk afgemaakt.","I have finished my work.",2,"af (finished) + maken (make)"],
["geslaagd","passed (exam)","Ik ben geslaagd voor het examen.","I passed the exam.",2,"ge- + slagen (succeed)"],
["weinig","not a lot","Ik heb weinig geld.","I have not a lot of money.",2],
["telefonisch spreekuur","telephone hours","Het telefonisch spreekuur is van negen tot tien.","Telephone hours are from nine to ten.",2,"telefoon (phone) + spreken (speak) + uur (hour)"],
["vakantie","holidays","Ik ga in juli op vakantie.","I am going on holiday in July.",2],
["schuiven","slide","Schuif de stoel naar links.","Slide the chair to the left.",2],
["volgorde","sequence/order","Zet de boeken op volgorde.","Put the books in order.",2,"volgen (follow) + orde (order)"],
["boven","up/upstairs","Mijn slaapkamer is boven.","My bedroom is upstairs.",2],
["beneden","down/downstairs","Kom even beneden.","Come down for a moment.",2,"be- + neder (low/down)"],
["door elkaar","mixed up","Alles ligt door elkaar.","Everything is mixed up.",2,"door (through) + elkaar (each other)"],
["niet alleen","not only","Niet alleen ik, maar ook zij.","Not only me, but also her.",2,"niet (not) + alleen (only)"],
["moeite","trouble/effort","Ik heb moeite met Nederlands.","I have trouble with Dutch.",2],
["sommige","some","Sommige mensen houden van regen.","Some people like rain.",2],
["hoe lang","how long","Hoe lang ben je hier al?","How long have you been here?",2,"hoe (how) + lang (long)"],
["ruilen","swap/exchange","Kan ik dit ruilen?","Can I swap this?",2],
["eerste","first","Dit is mijn eerste keer.","This is my first time.",2],
["klantenkaart","customer card","Heeft u een klantenkaart?","Do you have a customer card?",2,"klant (customer) + kaart (card)"],
["nieuw","new","Ik heb een nieuwe telefoon.","I have a new phone.",2],
["dweilen","mop the floor","Ik moet de vloer dweilen.","I have to mop the floor.",2],
["deden","did (past of doen)","Wat deden jullie gisteren?","What did you do yesterday?",2,"past tense of doen (do)"],
["1 keer","one time","Ik ben maar 1 keer geweest.","I have only been once.",2],
["vies","dirty","De keuken is vies.","The kitchen is dirty.",2],
["derde","third","Dit is de derde keer.","This is the third time.",2],

// --- Mock 3 ---
["leeftijd","age","Wat is je leeftijd?","What is your age?",3,"leven (live) + tijd (time)"],
["laatste","last","Dit is mijn laatste les.","This is my last lesson.",3],
["verkopers","salespeople","De verkopers zijn vriendelijk.","The salespeople are friendly.",3,"verkopen (sell) + -er"],
["stoppen","stop","Ik moet stoppen met roken.","I have to stop smoking.",3],
["bijzonder","special","Dit is een bijzondere dag.","This is a special day.",3,"bij (by) + zonder (without) → set apart"],
["feest","party","Het feest begint om acht uur.","The party starts at eight.",3],
["kantine","canteen","We eten in de kantine.","We eat in the canteen.",3],
["afscheid nemen","say goodbye","We nemen afscheid van onze collega.","We say goodbye to our colleague.",3,"af (off) + scheiden (separate) + nemen (take)"],
["gezellig","cozy","Het is gezellig bij jullie thuis.","It is cozy at your house.",3,"gezel (companion) + -ig"],
["straks","later","Ik zie je straks.","I will see you later.",3],
["druk","busy","Het is hier erg druk.","It is very busy here.",3],
["genoeg","enough","Ik heb genoeg gegeten.","I have eaten enough.",3],
["blijven","stay","Ik blijf vanavond thuis.","I am staying home tonight.",3],
["schoon","clean","Het huis is schoon.","The house is clean.",3],
["waarom","why","Waarom ben je laat?","Why are you late?",3,"waar (what) + om (for)"],
["minder","less","Ik eet minder suiker.","I eat less sugar.",3],
["vaker","more often","We moeten elkaar vaker zien.","We should see each other more often.",3,"vaak (often) + -er (more)"],
["hoe vaak","how often","Hoe vaak ga je sporten?","How often do you exercise?",3,"hoe (how) + vaak (often)"],
["vertrekken","leave","We vertrekken om zes uur.","We are leaving at six o'clock.",3,"ver- + trekken (pull, go)"],
["overdag","during the day","Overdag werk ik op kantoor.","During the day I work at the office.",3,"over (through) + dag (day)"],
["'s avonds","in the evening","'s Avonds kijk ik tv.","In the evening I watch TV.",3,"des (of the) + avond (evening)"],
["vergadering","meeting","De vergadering begint om tien uur.","The meeting starts at ten.",3,"vergaderen (to gather) + -ing"],
["buurt","neighbourhood","Ik woon in een rustige buurt.","I live in a quiet neighbourhood.",3],
["afspreken","make an appointment/meet","Zullen we morgen afspreken?","Shall we meet tomorrow?",3,"af (off) + spreken (speak) → to agree"],
["activiteit","activity","Welke activiteit kies je?","Which activity do you choose?",3],
["buurbewoners","residents/neighbours","De buurbewoners helpen elkaar.","The neighbours help each other.",3,"buur (neighbour) + bewoner (resident, from wonen 'live')"],
["kosten","costs","Wat zijn de kosten?","What are the costs?",3],
["uitrekenen","calculate","Ik moet de prijs uitrekenen.","I have to calculate the price.",3,"uit (out) + rekenen (calculate)"],
["duurder","more expensive","Dit is duurder dan ik dacht.","This is more expensive than I thought.",3,"duur (expensive) + -der (more)"],
["sturen","send","Ik ga je een mail sturen.","I am going to send you an email.",3],
["moeten","must","Ik moet nu naar huis.","I must go home now.",3],
["iedereen","everybody","Iedereen is welkom.","Everybody is welcome.",3,"ieder (every) + een (one)"],
["vinden","opinion/think","Wat vind je van het plan?","What is your opinion of the plan?",3],
["opsturen","send","Kun je mij de foto opsturen?","Can you send me the photo?",3,"op (up) + sturen (send) → send off"],
["toen","then/when (past)","Toen ik klein was, woonde ik hier.","When I was small, I lived here.",3],
["spelletjes","games","We spelen spelletjes op het feest.","We play games at the party.",3,"spel (game) + -etje (diminutive)"],
["pannenkoeken","pancakes","We eten pannenkoeken met stroop.","We eat pancakes with syrup.",3,"pan (pan) + koek (cake)"],
["hoe duur","how expensive","Hoe duur is dit boek?","How expensive is this book?",3,"hoe (how) + duur (expensive)"],
["vorig jaar","last year","Vorig jaar ben ik verhuisd.","Last year I moved.",3,"vorig (previous) + jaar (year)"],
["groeien","grow/expand","De plant groeit snel.","The plant grows fast.",3],
["bekend","famous","Hij is een bekend schrijver.","He is a famous writer.",3,"be- + kennen (know) → known"],
["vriendelijk","friendly/kind","De buurman is heel vriendelijk.","The neighbour is very friendly.",3,"vriend (friend) + -elijk (-ly)"],
["tevreden","satisfied","Ik ben tevreden met mijn werk.","I am satisfied with my work.",3,"te (to) + vrede (peace)"],
["doordeweeks","throughout the week","Doordeweeks werk ik veel.","Throughout the week I work a lot.",3,"door (through) + de week (the week)"],
["ervaring","experience","Ik heb veel ervaring met koken.","I have a lot of experience cooking.",3,"varen (to fare/travel) + -ing"],
["voordeel","advantage","Dit heeft een groot voordeel.","This has a big advantage.",3,"voor (for) + deel (part)"],
["nadeel","disadvantage","Het nadeel is dat het duur is.","The disadvantage is that it is expensive.",3,"na (after) + deel (part)"],
["omgaan met","to handle","Ik kan goed omgaan met kinderen.","I am good at handling children.",3,"om (around) + gaan (go) + met (with)"],
["beschikbaar","available","Ik ben morgen beschikbaar.","I am available tomorrow.",3,"beschikken (arrange/dispose) + -baar (-able)"],
["eerder","earlier","Kom eerder als je wilt.","Come earlier if you want.",3,"eer (before) + -der (more)"],
["plekken","places","Er zijn nog twee plekken vrij.","There are still two places free.",3],
["geschiedenis","history","Ik hou van geschiedenis.","I love history.",3,"geschieden (to happen) + -is"],
["vertellen","tell","Kun je het verhaal vertellen?","Can you tell the story?",3,"ver- + tellen (count/tell)"],
["oefenen","practice","Ik moet meer Nederlands oefenen.","I have to practice Dutch more.",3],
["bezoek","visitors","We krijgen vandaag bezoek.","We are having visitors today.",3,"be- + zoeken (seek) → visit"],
["gisteren","yesterday","Gisteren was het mooi weer.","Yesterday the weather was nice.",3],
["samen","together","We koken samen het eten.","We cook the food together.",3],
["zoeken","looking for/search","Ik zoek mijn sleutels.","I am looking for my keys.",3],
["winkels","shops","De winkels gaan om negen uur open.","The shops open at nine.",3],
["daarover","about that","Daarover wil ik graag praten.","I would like to talk about that.",3,"daar (there) + over (about)"],
["informatie","information","Ik heb meer informatie nodig.","I need more information.",3],
["werkrooster","work schedule","Mijn werkrooster verandert.","My work schedule is changing.",3,"werk (work) + rooster (schedule)"],
["probleem","problem","Ik heb een probleem met mijn computer.","I have a problem with my computer.",3],
["gebroken","broken","Mijn telefoon is gebroken.","My phone is broken.",3,"ge- + breken (break)"],
["laten weten","let know","Laat me even weten of je komt.","Let me know if you are coming.",3,"laten (let) + weten (know)"],
["gereedschap","tools","Ik heb gereedschap nodig.","I need tools.",3,"gereed (ready) + -schap (-ness)"],
["theorieboek","theory book","Ik leer uit het theorieboek.","I study from the theory book.",3,"theorie (theory) + boek (book)"],
["bestellen","order","Ik wil een pizza bestellen.","I want to order a pizza.",3,"be- + stellen (put/place)"],
["soorten","types/varieties","Er zijn veel soorten kaas.","There are many varieties of cheese.",3],
["meubel","furniture","Dit meubel is van hout.","This piece of furniture is made of wood.",3],
["ontwerpen","design","Hij gaat een huis ontwerpen.","He is going to design a house.",3,"ont- + werpen (throw) → to design"],
["inschrijven","register","Je moet je voor de cursus inschrijven.","You must register for the course.",3,"in (in) + schrijven (write)"],
["het enige","the only thing","Dat is het enige wat ik wil.","That is the only thing I want.",3],
["hout","wood","De tafel is van hout.","The table is made of wood.",3],
["daarmee","with that","Daarmee ben ik klaar.","I am done with that.",3,"daar (there) + mee (with)"],
["op tijd","on time","Kom op tijd voor de les.","Come on time for the lesson.",3,"op (on) + tijd (time)"],
["afmelden","log out/unregister","Ik moet me afmelden voor de cursus.","I have to log out of the course.",3,"af (off) + melden (report)"],
["verhuizen","move (house)","We gaan volgende maand verhuizen.","We are going to move next month.",3,"ver- + huis (house)"],
["tandarts","dentist","Ik ga naar de tandarts.","I am going to the dentist.",3,"tand (tooth) + arts (doctor)"],
["helaas","unfortunately","Helaas kan ik niet komen.","Unfortunately I cannot come.",3],
["verplaatst","rescheduled","De vergadering is verplaatst.","The meeting has been rescheduled.",3,"ver- + plaats (place)"],
["hetzelfde","same","Ik bestel hetzelfde als jij.","I will order the same as you.",3,"het (the) + zelf (self) + -de"],
["voldoende","enough","Ik heb voldoende geld.","I have enough money.",3,"vol (full) + doen (do)"],
["namelijk","namely","Ik ben moe, namelijk omdat ik laat sliep.","I am tired, namely because I slept late.",3,"naam (name) + -lijk (-ly)"],
["vakantierooster","holiday schedule","Het vakantierooster is klaar.","The holiday schedule is ready.",3,"vakantie (holiday) + rooster (schedule)"],
["aanvragen","apply for","Ik wil verlof aanvragen.","I want to apply for leave.",3,"aan (to) + vragen (ask)"],
["aan het werk","at work","Ik ben aan het werk.","I am at work.",3,"aan (at) + het werk (the work)"],
["balie","desk/counter","Meld je bij de balie.","Report at the desk.",3],
["nodig","needed","Ik heb hulp nodig.","I need help.",3],
["telefoon opnemen","answer the phone","Kun je de telefoon opnemen?","Can you answer the phone?",3,"telefoon (phone) + op (up) + nemen (take)"],
["achter elkaar","in a row","Drie dagen achter elkaar gewerkt.","Worked three days in a row.",3,"achter (behind) + elkaar (each other)"],

// --- Mock 4 ---
["weten","to know","Ik weet het antwoord niet.","I do not know the answer.",4],
["kennis","knowledge","Hij heeft veel kennis over geschiedenis.","He has a lot of knowledge about history.",4,"kennen (know) + -nis"],
["reden","reason","Wat is de reden van je bezoek?","What is the reason for your visit?",4],
["praten","talk","We praten elke dag met elkaar.","We talk to each other every day.",4],
["studeren","study","Ik ga vanavond studeren voor de toets.","I am going to study for the test tonight.",4],
["werken","work","Mijn vader werkt in een ziekenhuis.","My father works in a hospital.",4],
["dicht","closed","De winkel is vandaag dicht.","The shop is closed today.",4],
["taken","tasks","Ik heb veel taken op het werk.","I have many tasks at work.",4],
["veranderen","change","Ik wil mijn baan veranderen.","I want to change my job.",4,"ver- + ander (other)"],
["winkel","shop","De winkel opent om negen uur.","The shop opens at nine o'clock.",4],
["volgende week","next week","Volgende week ga ik op vakantie.","Next week I am going on holiday.",4,"volgen (follow) + week (week)"],
["horen","hear","Ik kan je niet goed horen.","I cannot hear you well.",4],
["maand","month","Deze maand is heel druk.","This month is very busy.",4],
["tot","until","De winkel is open tot zes uur.","The shop is open until six o'clock.",4],
["mensen","people","Er zijn veel mensen in de stad.","There are many people in the city.",4],
["rooster","schedule","Mijn rooster verandert elke week.","My schedule changes every week.",4],
["natuurlijk","of course","Natuurlijk help ik je graag.","Of course I am happy to help you.",4,"natuur (nature) + -lijk (-ly)"],
["allemaal","all","We gaan allemaal naar het feest.","We are all going to the party.",4,"alle (all) + maal (time/instance)"],
["misschien","maybe","Misschien regent het morgen.","Maybe it will rain tomorrow.",4,"mis (miss) + schien (happen) → may happen"],
["volgende maand","next month","Volgende maand ben ik jarig.","Next month is my birthday.",4,"volgen (follow) + maand (month)"],
["iedere","every","Iedere ochtend drink ik koffie.","Every morning I drink coffee.",4],
["langer","longer","Hij blijft langer dan verwacht.","He stays longer than expected.",4,"lang (long) + -er (more)"],
["willen","want","Ik wil een nieuwe fiets.","I want a new bicycle.",4],
["omdat","because","Ik blijf thuis omdat ik ziek ben.","I stay home because I am sick.",4,"om (for) + dat (that)"],
["werktijden","working times","Mijn werktijden zijn van negen tot vijf.","My working times are from nine to five.",4,"werk (work) + tijden (times)"],
["cursus","course","Ik volg een cursus Nederlands.","I am taking a Dutch course.",4],
["repareren/maken","fix/make","Kun je mijn fiets repareren?","Can you fix my bicycle?",4],
["baan","job","Ze zoekt een nieuwe baan.","She is looking for a new job.",4],
["opleiding","education/training","Welke opleiding heb je gedaan?","Which education did you do?",4,"op (up) + leiden (lead) → training"],
["van tevoren","in advance","Bel even van tevoren.","Call in advance please.",4,"van (from) + voor (before)"],
["folder","brochure","Hier is een folder met informatie.","Here is a brochure with information.",4],
["overzicht/schema","overview/schedule","Ik heb een overzicht gemaakt.","I made an overview.",4,"over (over) + zien (see) → overview"],
["verschillende/diverse","various","Er zijn verschillende kleuren.","There are various colors.",4],
["waar","where","Waar woon jij?","Where do you live?",4],
["bellen","call","Ik ga mijn moeder bellen.","I am going to call my mother.",4],
["normaal","normal","Normaal sta ik om zeven uur op.","Normally I get up at seven.",4],
["andere","other","Ik wil de andere kleur.","I want the other color.",4],
["dicht/gesloten","closed","Het museum is vandaag gesloten.","The museum is closed today.",4,"ge- + sluiten (close)"],
["de weg","the road/way","Ik weet de weg niet.","I do not know the road/way.",4],
["bushalte","bus stop","De bushalte is om de hoek.","The bus stop is around the corner.",4,"bus + halte (stop)"],
["opstappen","get on the bus","Waar moet ik opstappen?","Where should I get on the bus?",4,"op (on) + stappen (step)"],
["gemeente","municipality","Ik moet naar de gemeente.","I have to go to the municipality.",4,"gemeen (common) + -te"],
["mogen","may","Mag ik even langskomen?","May I come by for a moment?",4],
["kermis","fair","De kermis is in de stad.","The fair is in town.",4],
["gebouw","building","Dat gebouw is heel oud.","That building is very old.",4,"ge- + bouwen (build)"],
["studiecentrum","study centre","Ik leer in het studiecentrum.","I study at the study centre.",4,"studie (study) + centrum (centre)"],
["lokaal","classroom","Het lokaal is op de tweede verdieping.","The classroom is on the second floor.",4],
["begane grond","ground floor","De receptie is op de begane grond.","The reception is on the ground floor.",4,"begaan (walk on) + grond (ground)"],
["vanaf","from","Vanaf maandag begin ik te werken.","From Monday I start working.",4,"van (from) + af (off)"],
["weer","again","Tot ziens, tot de volgende keer weer!","Goodbye, see you again next time!",4],
["verbouwing","renovation","Het huis is in verbouwing.","The house is under renovation.",4,"ver- + bouwen (build)"],
["doorgaan","take place/continue","De les gaat vandaag door.","The class takes place today.",4,"door (through) + gaan (go)"],
["overslaan","skip","Ik wil het ontbijt overslaan.","I want to skip breakfast.",4,"over (over) + slaan (strike) → skip over"],
["de regels","the rules","Volg de regels van het spel.","Follow the rules of the game.",4],
["klanten","customers","De winkel heeft veel klanten.","The shop has many customers.",4],
["stofzuigen","vacuum (clean)","Ik ga de kamer stofzuigen.","I am going to vacuum the room.",4,"stof (dust) + zuigen (suck)"],
["speelgoed","toys","De kinderen ruimen het speelgoed op.","The children tidy up the toys.",4,"spelen (play) + goed (goods)"],
["stil zitten","sit still","Kinderen kunnen niet lang stil zitten.","Children cannot sit still for long.",4,"stil (still) + zitten (sit)"],
["netjes","decent/neat","Hij ziet er netjes uit.","He looks decent/neat.",4,"net (neat) + -jes"],
["schoonmaken","clean","Ik ga het huis schoonmaken.","I am going to clean the house.",4,"schoon (clean) + maken (make)"],
["alleen","only/alone","Ik woon alleen.","I live alone.",4,"al (all) + een (one)"],
["opletten","pay attention","Let goed op in de les.","Pay attention in class.",4,"op (up) + letten (heed)"],
["fijn","fine/nice","Wat een fijne dag!","What a fine day!",4],
["elkaar","each other","We helpen elkaar.","We help each other.",4,"elk (each) + aar (other)"],
["te veel","too much","Dit is te veel werk.","This is too much work.",4,"te (too) + veel (much)"],
["maar","but","Ik wil komen, maar ik kan niet.","I want to come, but I cannot.",4],
["inhalen","catch up","Ik moet de les inhalen.","I have to catch up the lesson.",4,"in (in) + halen (fetch) → catch up"],
["missen","miss","Ik mis mijn familie.","I miss my family.",4],
["vervelend","annoying","Wat vervelend voor je.","How annoying for you.",4,"vervelen (to bore) + -end"],
["toets","test","Morgen heb ik een toets.","Tomorrow I have a test.",4],
["woordenboek","dictionary","Ik zoek het woord in het woordenboek.","I look up the word in the dictionary.",4,"woord (word) + boek (book)"],
["slim","smart","Mijn zoon is heel slim.","My son is very smart.",4],
["opdrachten","assignments","De opdrachten zijn moeilijk.","The assignments are difficult.",4,"op (up) + dragen (carry) → assignment"],
["trouwens","by the way","Trouwens, hoe gaat het met je moeder?","By the way, how is your mother?",4,"trouw (true) + -ens"],
["foto's","pictures","Ik laat je de foto's zien.","I will show you the pictures.",4],
["knipbeurt","haircut","Ik heb een knipbeurt nodig.","I need a haircut.",4,"knippen (cut) + beurt (turn)"],
["een afspraak maken","make an appointment","Ik wil een afspraak maken.","I want to make an appointment.",4,"afspraak (appointment, af + spraak) + maken (make)"],
["nieuwsbrief","newsletter","De nieuwsbrief komt elke maand.","The newsletter comes every month.",4,"nieuws (news) + brief (letter)"],
["dochtertje","little daughter","Haar dochtertje is drie jaar oud.","Her little daughter is three years old.",4,"dochter (daughter) + -tje (diminutive)"],
["wassen","wash","Ik moet mijn handen wassen.","I have to wash my hands.",4],
["knippen","cut","Mag ik mijn haar laten knippen?","May I have my hair cut?",4],
["vieren","celebrate","We vieren mijn verjaardag.","We celebrate my birthday.",4],
["getrouwd","married","Mijn zus is getrouwd.","My sister is married.",4,"ge- + trouwen (marry, from trouw 'loyal')"],
["zwembad","swimming pool","We gaan naar het zwembad.","We are going to the swimming pool.",4,"zwemmen (swim) + bad (bath)"],
["lied","song","Ik ken dat lied.","I know that song.",4],
["ik heb geen idee","I have no idea","Ik heb geen idee waar hij is.","I have no idea where he is.",4],
["dat weet ze niet","she doesn't know that","Vraag het haar, dat weet ze niet.","Ask her, she doesn't know.",4],
["feestdagen","holidays (festive)","Tijdens de feestdagen zijn we thuis.","During the holidays we are at home.",4,"feest (party/festival) + dagen (days)"],
["de rest","the remaining part","De rest doe ik morgen.","The remaining part I will do tomorrow.",4],
["afdeling","department","Welke afdeling zoekt u?","Which department are you looking for?",4,"af- + delen (divide) → department"],
["de reden","the reason","De reden is dat ik ziek ben.","The reason is that I am sick.",4],
["simpel","simple","Het is heel simpel.","It is very simple.",4],

// --- Mock 5 ---
["vóór","before","Stuur het formulier vóór vrijdag.","Send the form before Friday.",5],
["ten minste/minimaal","at least","Je hebt ten minste twee jaar ervaring nodig.","You need at least two years of experience.",5],
["maximaal/ten hoogste","at most / maximum","Je mag maximaal drie dagen per week thuiswerken.","You can work from home at most three days a week.",5],
["opzegtermijn","notice period","De opzegtermijn is één maand.","The notice period is one month.",5,"opzeggen (cancel) + termijn (period)"],
["behalve/uitgezonderd","except / excluded","Iedereen mag komen, behalve kinderen onder de zes.","Everyone may come, except children under six.",5,"uit (out) + zonderen (to separate) → excepted"],
["gedurende","during","Gedurende de vakantie is de winkel gesloten.","During the holiday the shop is closed.",5],
["tenzij","unless","We gaan wandelen, tenzij het regent.","We're going for a walk, unless it rains.",5],
["tijdelijk","temporary / temporarily","Ik woon hier maar tijdelijk.","I only live here temporarily.",5,"tijd (time) + -elijk (adj. suffix)"],
["vervallen","cancelled / expired","De les van morgen vervalt.","Tomorrow's class is cancelled.",5],
["aansluitend/direct na","immediately after","Aansluitend op de les is er een pauze.","Immediately after the class there is a break.",5,"aan (on) + sluiten (to connect) → immediately following"],
["vergunning","permit","Je hebt een vergunning nodig om te verbouwen.","You need a permit to renovate.",5],
["voorwaarden","terms & conditions","Lees de voorwaarden goed door.","Read the terms and conditions carefully.",5,"voor (before) + waarden (values) → conditions"],
["toestemming","permission / consent","Ik heb toestemming van mijn baas nodig.","I need permission from my boss.",5,"toe (towards) + stemmen (to agree/vote) → consent"],
["onderhoudswerkzaamheden","maintenance work","Er zijn onderhoudswerkzaamheden aan het spoor.","There is maintenance work on the railway.",5,"onderhoud (maintenance) + werkzaamheden (works)"],
["afvalinzameling","waste collection","De afvalinzameling is op maandag.","Waste collection is on Monday.",5,"afval (waste) + inzameling (collection)"],
["grofvuil","bulky waste","Je kunt grofvuil laten ophalen.","You can have bulky waste picked up.",5,"grof (coarse/bulky) + vuil (waste)"],
["parkeerbeleid","parking policy","De gemeente wijzigt het parkeerbeleid.","The municipality is changing the parking policy.",5,"parkeren (park) + beleid (policy)"],
["blauwe zone","disc parking zone","In de blauwe zone mag je twee uur parkeren.","In the disc parking zone you may park for two hours.",5],
["berichtenbox","digital mailbox","Ik kreeg een bericht in mijn berichtenbox.","I got a message in my digital mailbox.",5,"bericht (message) + box (box)"],
["ziekmelden","to call in sick","Ik moet me vandaag ziekmelden.","I have to call in sick today.",5,"ziek (sick) + melden (report)"],
["vereiste/verplicht","requirement / mandatory","Een diploma is een vereiste voor deze baan.","A diploma is a requirement for this job.",5],
["ervaring is een pré","experience is an advantage","Nederlands spreken is geen vereiste, maar ervaring is een pré.","Speaking Dutch isn't required, but experience is an advantage.",5],
["aanwezigheid","attendance / presence","Je aanwezigheid is verplicht.","Your attendance is mandatory.",5,"aanwezig (present) + -heid (-ness)"],
["behalen/slagen","to pass / achieve","Ik hoop mijn diploma te behalen.","I hope to achieve my diploma.",5],
["afzeggen/annuleren","to cancel","Ik moet mijn afspraak afzeggen.","I have to cancel my appointment.",5,"af (off) + zeggen (say) → to cancel"],
["vergoeding","compensation / reimbursement","Je krijgt een vergoeding voor de reiskosten.","You get reimbursement for the travel costs.",5],
["voorschrift/recept","prescription","De dokter geeft me een recept.","The doctor gives me a prescription.",5,"voor (before) + schrift (writing) → prescription"],
["lege maag","empty stomach","Neem deze pillen op een lege maag.","Take these pills on an empty stomach.",5],
["bijwerkingen","side effects","Dit medicijn kan bijwerkingen hebben.","This medicine can have side effects.",5,"bij (side) + werking (effect)"],
["spoedgeval","emergency","Bel 112 bij een spoedgeval.","Call 112 in case of an emergency.",5,"spoed (urgency) + geval (case)"],
["nabloeding","prolonged bleeding","Bel de dokter bij een nabloeding.","Call the doctor in case of prolonged bleeding.",5,"na (after) + bloeding (bleeding)"],
["betreden","to enter","Het is verboden het terrein te betreden.","It is forbidden to enter the site.",5],
["veiligheidsvoorschrift","safety regulation","Volg altijd het veiligheidsvoorschrift.","Always follow the safety regulation.",5,"veiligheid (safety) + voorschrift (regulation)"],
["slecht ter been","having difficulty walking","Mijn oma is slecht ter been.","My grandma has difficulty walking.",5],
["afgeprijsd","discounted","Deze jas is afgeprijsd.","This jacket is discounted.",5,"af (off) + prijzen (to price)"],
["wisselbon/tegoedbon","voucher / store credit","Ik kreeg een wisselbon voor het kapotte product.","I got a voucher for the broken product.",5,"wissel (exchange) / tegoed (credit) + bon (voucher)"],
["kassabon","store receipt","Bewaar altijd je kassabon.","Always keep your store receipt.",5,"kassa (register) + bon (receipt)"],
["vervangend vervoer","replacement transport","Er is vervangend vervoer wegens werkzaamheden.","There is replacement transport due to maintenance work.",5,"vervangend (replacement) + vervoer (transport)"],
["reistijd","travel time","De reistijd is ongeveer een uur.","The travel time is about an hour.",5,"reis (trip) + tijd (time)"],
["vertraging","delay","De trein heeft vertraging.","The train has a delay.",5],
["rekening houden met","to take into account","Houd rekening met drukte op vrijdag.","Take into account busy times on Friday.",5],
["in rekening brengen","to charge a fee","De winkel brengt verzendkosten in rekening.","The shop charges shipping costs.",5],
["vol","full","De trein zit helemaal vol.","The train is completely full.",5],
["leeg","empty","De fles is leeg.","The bottle is empty.",5],
["gevaarlijk","dangerous","Dat is een gevaarlijke weg.","That is a dangerous road.",5,"gevaar (danger) + -lijk (adj. suffix)"],
["veilig","safe","Dit gebied is veilig.","This area is safe.",5],
["optioneel","optional","Deze cursus is optioneel.","This course is optional.",5],
["zakken","to fail (an exam)","Ik hoop niet te zakken voor mijn examen.","I hope not to fail my exam.",5],
["juist/goed","correct","Dat antwoord is juist.","That answer is correct.",5],
["onjuist/fout","incorrect","Dat antwoord is onjuist.","That answer is incorrect.",5,"on- (not) + juist (correct) → incorrect"],
["vertrek","departure","Het vertrek is om acht uur.","The departure is at eight o'clock.",5],
["aankomst","arrival","De aankomst is vertraagd.","The arrival is delayed.",5,"aan (at) + komst (coming, from komen) → arrival"],
["voorkant/voorzijde","front","Parkeer aan de voorkant van het gebouw.","Park at the front of the building.",5,"voor (front) + kant/zijde (side)"],
["achterkant/achterzijde","back","De ingang is aan de achterkant.","The entrance is at the back.",5,"achter (behind) + kant/zijde (side)"],
["ingang","entrance","De ingang is aan de linkerkant.","The entrance is on the left side.",5,"in (in) + gang (walkway) → entrance"],
["uitgang","exit","Volg de borden naar de uitgang.","Follow the signs to the exit.",5,"uit (out) + gang (walkway) → exit"],
["naar boven","upstairs / going up","Neem de trap naar boven.","Take the stairs going up.",5],
["naar beneden","downstairs / going down","Neem de lift naar beneden.","Take the lift going down.",5],
["links","left","Sla linksaf bij het kruispunt.","Turn left at the intersection.",5],
["rechts","right","Het station is aan de rechterkant.","The station is on the right side.",5],
["dichtbij","nearby","De supermarkt is dichtbij.","The supermarket is nearby.",5,"dicht (close) + bij (by/near)"],
["ver weg","far away","Het strand is ver weg.","The beach is far away.",5],
["goedkoop","cheap","Deze schoenen zijn goedkoop.","These shoes are cheap.",5,"goed (good) + koop (deal/purchase) → cheap"],
["duur","expensive","Dat restaurant is erg duur.","That restaurant is very expensive.",5],
["betaald","paid","Dit is een betaalde parkeerplaats.","This is a paid parking spot.",5],
["stijgen/toenemen","to increase","De prijzen blijven stijgen.","Prices keep increasing.",5,"toe (increasingly) + nemen (take) → to increase"],
["dalen/afnemen","to decrease","Het aantal klachten daalt.","The number of complaints is decreasing.",5,"af (off) + nemen (take) → to decrease"],
["alles","everything","Ik heb alles opgeschreven.","I wrote everything down.",5],
["vroeg","early","We moeten vroeg opstaan.","We have to get up early.",5],
["laat","late","Sorry dat ik laat ben.","Sorry that I'm late.",5],
["open","open","De winkel is open tot zes uur.","The shop is open until six o'clock.",5],
["toegestaan","allowed","Roken is hier niet toegestaan.","Smoking is not allowed here.",5,"toe (to) + staan (stand) → to allow"],
["verboden","forbidden","Parkeren is hier verboden.","Parking is forbidden here.",5],
["vrij","free / available","Is deze stoel nog vrij?","Is this seat still free?",5],
["bezet","occupied / busy","Het toilet is bezet.","The toilet is occupied.",5],
["vast/permanent","permanent","Na een jaar krijg ik een vast contract.","After a year I get a permanent contract.",5],
["vertraagd","delayed","Mijn vlucht is vertraagd.","My flight is delayed.",5],
];
